jobs:
  python_ottawa_transit:
    docker:
      - image: "circleci/python:3.6"
    steps:
      - checkout:
          path: ~/repo
      - run:
          command: |
              pip install --user poetry
          name: "Installing poetry"
      - run:
          command: |
              export PATH="/home/circleci/.local/bin:$PATH"
              poetry dev
              poetry run pytest --cov=python_ottawa_transit
          name: "Running tests"
    working_directory: ~/repo
workflows:
  version: 2
  tracker:
    jobs:
      - python_ottawa_transit
